version: '3.8'

services:
  app:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: "your-secure-256-bit-secret-key-change-in-production-please"
      JWT_EXPIRATION_MS: "86400000"
      SERVER_PORT: "8080"
    volumes:
      - app_data:/app/data

volumes:
  app_data: