import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Alert,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Colors } from '../../constants/colors';
import { MOCK_LENDS, MOCK_REPAYMENTS } from '../../constants/mockData';
import PrimaryButton from '../../components/ui/PrimaryButton';
import OutlinedButton from '../../components/ui/OutlinedButton';
import { formatDate, formatCurrency } from '../../utils/formatCurrency';

export default function ReceiptPreviewScreen() {
  const router = useRouter();
  const { lendId } = useLocalSearchParams<{ lendId: string }>();

  const lend = MOCK_LENDS.find((l) => l.id === Number(lendId)) ?? MOCK_LENDS[0];
  const repayment = MOCK_REPAYMENTS.find((r) => r.lendId === lend.id);
  const receiptNo = `RCP-${String(lend.id).padStart(5, '0')}`;
  const today = formatDate(new Date().toISOString());

  return (
    <SafeAreaView style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
          <Ionicons name="arrow-back" size={24} color={Colors.textPrimary} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Receipt Preview</Text>
        <TouchableOpacity
          onPress={() => Alert.alert('Share', 'Sharing receipt...')}
          style={styles.shareBtn}
        >
          <Ionicons name="share-outline" size={24} color={Colors.primary} />
        </TouchableOpacity>
      </View>

      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}>
        {/* Receipt Card */}
        <View style={styles.receiptCard}>
          {/* Top Section */}
          <View style={styles.receiptHeader}>
            <Text style={styles.receiptLogo}>💰 LendWise</Text>
            <Text style={styles.receiptTitle}>Payment Receipt</Text>
          </View>
          <View style={styles.divider} />

          {/* Receipt Meta */}
          <View style={styles.receiptRow}>
            <Text style={styles.receiptKey}>Receipt No.</Text>
            <Text style={styles.receiptValue}>{receiptNo}</Text>
          </View>
          <View style={styles.receiptRow}>
            <Text style={styles.receiptKey}>Date</Text>
            <Text style={styles.receiptValue}>{today}</Text>
          </View>

          <View style={styles.divider} />

          {/* Parties */}
          <View style={styles.receiptRow}>
            <Text style={styles.receiptKey}>Lender</Text>
            <Text style={styles.receiptValue}>Yasser Al-Ansari</Text>
          </View>
          <View style={styles.receiptRow}>
            <Text style={styles.receiptKey}>Borrower</Text>
            <View style={styles.valueCol}>
              <Text style={styles.receiptValue}>{lend.contact}</Text>
              <Text style={styles.receiptSub}>+973 3300 0000</Text>
            </View>
          </View>

          <View style={styles.divider} />

          {/* Amounts */}
          <View style={styles.receiptRow}>
            <Text style={styles.receiptKey}>Original Amount</Text>
            <Text style={styles.receiptValue}>{formatCurrency(lend.amount)}</Text>
          </View>
          <View style={styles.receiptRow}>
            <Text style={styles.receiptKey}>Amount Paid</Text>
            <Text style={[styles.receiptValue, { color: Colors.success }]}>
              {formatCurrency(lend.paid)}
            </Text>
          </View>
          <View style={styles.receiptRow}>
            <Text style={styles.receiptKey}>Remaining Balance</Text>
            <Text style={[styles.receiptValue, { color: Colors.danger }]}>
              {formatCurrency(lend.amount - lend.paid)}
            </Text>
          </View>
          <View style={styles.receiptRow}>
            <Text style={styles.receiptKey}>Transfer Ref</Text>
            <Text style={styles.receiptValue}>{repayment?.ref ?? 'N/A'}</Text>
          </View>

          <View style={styles.divider} />

          {/* Acknowledgement */}
          <View style={styles.ackSection}>
            <Text style={styles.ackText}>✅ Acknowledged by {lend.contact}</Text>
            {lend.acknowledgedDate && (
              <Text style={styles.ackDate}>{formatDate(lend.acknowledgedDate)}</Text>
            )}
          </View>

          <View style={styles.divider} />

          {/* Footer */}
          <Text style={styles.receiptFooter}>Generated by LendWise</Text>
        </View>

        {/* Actions */}
        <View style={styles.actions}>
          <PrimaryButton
            title="⬇️ Download PDF"
            onPress={() => Alert.alert('Download', 'PDF download started...')}
          />
          <View style={styles.spacer} />
          <OutlinedButton
            title="⬆️ Share Receipt"
            onPress={() => Alert.alert('Share', 'Sharing receipt...')}
          />
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  backBtn: { padding: 4, marginRight: 8 },
  headerTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '600',
    color: Colors.textPrimary,
    textAlign: 'center',
  },
  shareBtn: { padding: 4 },
  scroll: { paddingHorizontal: 20, paddingBottom: 40 },
  receiptCard: {
    backgroundColor: Colors.card,
    borderRadius: 16,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
    marginBottom: 24,
  },
  receiptHeader: { alignItems: 'center', marginBottom: 16 },
  receiptLogo: { fontSize: 18, fontWeight: '700', color: Colors.primary, marginBottom: 4 },
  receiptTitle: { fontSize: 16, fontWeight: '600', color: Colors.textPrimary },
  divider: {
    height: 1,
    backgroundColor: Colors.border,
    marginVertical: 16,
    borderStyle: 'dashed',
  },
  receiptRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  receiptKey: {
    fontSize: 13,
    color: Colors.textSecondary,
    flex: 1,
  },
  receiptValue: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.textPrimary,
    textAlign: 'right',
    flex: 1,
  },
  valueCol: { alignItems: 'flex-end', flex: 1 },
  receiptSub: { fontSize: 11, color: Colors.textSecondary, marginTop: 2 },
  ackSection: {
    backgroundColor: '#D1FAE5',
    borderRadius: 10,
    padding: 12,
    alignItems: 'center',
  },
  ackText: { fontSize: 13, color: Colors.success, fontWeight: '600' },
  ackDate: { fontSize: 11, color: Colors.success, marginTop: 4 },
  receiptFooter: {
    textAlign: 'center',
    fontSize: 11,
    color: Colors.textSecondary,
  },
  actions: { gap: 0 },
  spacer: { height: 12 },
});
